import {chromium} from '../runtime/test-tools/node_modules/playwright-core/index.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {createServer} from '../server.mjs';
const ROOT=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const out=path.join(ROOT,'runtime','screenshots');fs.mkdirSync(out,{recursive:true});
let failNextReply=false;const requests=[];
const server=createServer({configured:true,base:'https://test.invalid/v1',key:'TEST_ONLY_KEY',model:'test-model'},{fetchImpl:async(url,options)=>{
 const body=JSON.parse(options.body);requests.push(body);
 const suggestion=body.messages[0].content.includes('表达助手');
 if(failNextReply&&!suggestion&&body.messages.length>1){failNextReply=false;return new Response('{}',{status:500})}
 const content=suggestion?JSON.stringify({suggestions:[{label:'自然招呼',text:'看到你留下的话题，就想来打个招呼。你会怎么安排这样的周末？'},{label:'继续了解',text:'你平时有喜欢散步的地方吗？'},{label:'轻松接话',text:'有一个不用赶时间的周末就很好。你呢？'}]}):body.messages.length===1?'连接成功':'很高兴收到你的消息。我喜欢傍晚沿河散步，你平时会怎么度过周末？';
 return new Response(JSON.stringify({choices:[{message:{content}}]}),{status:200,headers:{'Content-Type':'application/json'}});
}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const errors=[];let context;const unconfigured=createServer({configured:false,model:''});await new Promise(r=>unconfigured.listen(0,'127.0.0.1',r));
try{
 context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();page.on('pageerror',err=>errors.push(err.message));page.on('console',msg=>{if(msg.type()==='error'&&/Content Security Policy|Refused to execute|Refused to apply/.test(msg.text()))errors.push(msg.text())});
 await page.goto(url);await page.getByRole('button',{name:'AI 待检查',exact:true}).waitFor();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');
 await page.screenshot({path:path.join(out,'mobile-meet.png'),fullPage:true});
 await page.getByRole('button',{name:'AI 待检查',exact:true}).click();
 await page.getByRole('button',{name:'检查连接（会调用模型）',exact:true}).click();
 await page.getByRole('heading',{name:'连接已验证'}).waitFor();
 await page.getByRole('button',{name:'关闭面板'}).click();
 await page.getByRole('button',{name:'递张纸条',exact:false}).first().click();
 await page.getByLabel('纸条内容').fill('我喜欢散步，想和你聊聊。');
 await page.getByRole('button',{name:'拾言 · 三个建议',exact:true}).click();
 await page.getByRole('button',{name:/自然招呼/}).click();
 assert((await page.getByLabel('纸条内容').inputValue()).includes('打个招呼'));
 await page.getByLabel('纸条内容').fill('我喜欢散步，很高兴认识你。');
 await page.getByRole('button',{name:/^递出纸条/}).click();
 await page.getByRole('button',{name:'让 AI 回应这张纸条',exact:true}).click();
 await page.locator('.bubble').filter({hasText:'很高兴收到你的消息'}).waitFor();
 await page.getByLabel('聊天消息').fill('今天心情不错。');failNextReply=true;
 await page.getByRole('button',{name:/^发送/}).click();
 await page.getByRole('button',{name:'重试回复',exact:true}).waitFor();
 assert.equal(await page.locator('.bubble').filter({hasText:'今天心情不错。'}).count(),1);
 await page.getByRole('button',{name:'重试回复',exact:true}).click();
 await page.getByLabel('聊天消息').waitFor();
 assert.equal(await page.locator('.bubble').filter({hasText:'今天心情不错。'}).count(),1);
 await page.screenshot({path:path.join(out,'mobile-chat.png'),fullPage:true});
 await page.getByRole('button',{name:'心笺',exact:true}).click();
 await page.locator('#score-input').fill('73');await page.locator('#score-input').dispatchEvent('input');
 await page.locator('#memo').fill('PRIVATE_FEELING_73');await page.getByRole('button',{name:'保存这次感受'}).click();
 await page.getByRole('button',{name:'回望 · 确认意愿'}).click();
 await page.locator('#review-intent').selectOption('closer');await page.locator('#review-auth').check();
 await page.getByRole('button',{name:'确认本周期意愿'}).click();
 await page.getByRole('button',{name:'打开 Demo 控制面板'}).click();
 await page.locator('#demo-intent').selectOption('closer');await page.locator('#demo-auth').check();await page.getByRole('button',{name:'保存为本周期状态'}).click();await page.getByRole('button',{name:'关闭面板'}).click();
 await page.locator('.bottom-nav').getByRole('button',{name:'我的',exact:true}).click();
 assert((await page.locator('.score').first().innerText()).includes('73'));
 await page.locator('.feeling-card').first().getByRole('button',{name:'轻叩窗扉',exact:true}).click();
 await page.locator('#knock-consent').check();await page.getByRole('button',{name:'确认轻叩'}).click();
 await page.locator('#dialog').getByRole('heading',{name:'你的心意，有了回响。',exact:true}).waitFor();
 await page.screenshot({path:path.join(out,'mobile-mutual.png')});
 await page.getByRole('button',{name:'回到我的心笺'}).click();
 await page.reload();await page.getByRole('button',{name:'AI 待检查',exact:true}).waitFor();await page.locator('.bottom-nav').getByRole('button',{name:'我的',exact:true}).click();
 assert((await page.locator('.score').first().innerText()).includes('73'));assert.equal(await page.locator('.result-card').count(),1);
 await page.getByRole('button',{name:'打开 Demo 控制面板'}).click();await page.getByRole('button',{name:'推进 7 天',exact:true}).click();await page.locator('#demo-intent').selectOption('exploring');await page.getByRole('button',{name:'保存为本周期状态'}).click();await page.getByRole('button',{name:'关闭面板'}).click();
 await page.locator('.feeling-card').first().getByRole('button',{name:'回望',exact:true}).click();await page.locator('#review-auth').check();await page.getByRole('button',{name:'确认本周期意愿'}).click();
 await page.locator('.feeling-card').first().getByRole('button',{name:'轻叩窗扉',exact:true}).click();await page.locator('#knock-consent').check();await page.getByRole('button',{name:'确认轻叩'}).click();await page.locator('#dialog').getByRole('heading',{name:'本次暂未确认双向心意。',exact:true}).waitFor();await page.getByRole('button',{name:'回到我的心笺'}).click();
 await page.getByRole('button',{name:'打开 Demo 控制面板'}).click();await page.locator('#demo-person').selectOption('yu');await page.getByRole('button',{name:'模拟收到纸条',exact:true}).click();
 await page.getByRole('button',{name:'稍后再看',exact:true}).last().click();await page.locator('.tabs').getByRole('button',{name:'稍后再看',exact:true}).click();await page.getByRole('button',{name:'暂不接话',exact:true}).click();await page.getByRole('button',{name:'已归档',exact:true}).click();await page.locator('.note-card').filter({hasText:'已归档 · 不通知对方'}).waitFor();
 assert(!JSON.stringify(requests).includes('PRIVATE_FEELING_73'));
 await page.getByRole('button',{name:'打开 Demo 控制面板'}).click();await page.getByRole('button',{name:'重置全部演示数据'}).click();await page.getByRole('button',{name:'确认清除并重新开始'}).click();
 assert.equal(await page.locator('.person-card').count(),3);
 await page.setViewportSize({width:320,height:720});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'narrow mobile overflow');
 await page.setViewportSize({width:1440,height:1000});await page.mouse.move(0,0);await page.locator('#toast.show').waitFor({state:'hidden'});await page.screenshot({path:path.join(out,'desktop-meet.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'desktop overflow');
 // Separate unconfigured test server; never use real keys or change the running demo.
 await page.goto(`http://127.0.0.1:${unconfigured.address().port}`);await page.getByRole('button',{name:'配置 AI',exact:true}).waitFor();await page.getByRole('button',{name:'递张纸条',exact:false}).first().click();await page.getByRole('heading',{name:'尚未配置接口'}).waitFor();assert(await page.getByRole('button',{name:'检查连接（会调用模型）',exact:true}).isDisabled());
 await page.screenshot({path:path.join(out,'configuration.png')});
 assert.deepEqual(errors,[]);console.log('PASS: mobile + desktop overflow, configuration gate, suggestions, editable note, AI reply, failure retry without duplicate, private feelings, authorization, both outcomes, persistence, cycle advance, inbox save/archive, reset.');
 console.log('Screenshots saved in runtime/screenshots. All model responses in this test were explicitly mocked.');
}finally{await context?.close();await browser.close();server.closeAllConnections();unconfigured.closeAllConnections();await Promise.all([new Promise(r=>server.close(r)),new Promise(r=>unconfigured.close(r))])}
