import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as C from '../public/core.mjs';
const T=new Date('2026-09-26T12:00:00+08:00').getTime();
const fresh=()=>C.freshState(T);
function contact(s,id='xia'){const n=C.sendNote(s,id,'你好，很高兴认识你。',T);C.startNoteReply(s,n.id);C.finishReply(s,id,'很高兴认识你！',T)}
test('daily paper limits and no duplicate before reply',()=>{const s=fresh();C.sendNote(s,'xia','你好',T);assert.throws(()=>C.sendNote(s,'xia','再问一下',T));C.sendNote(s,'yu','你好',T);assert.throws(()=>C.sendNote(s,'ning','你好',T));s.offsetDays++;assert.equal(C.noteEligibility(s,'ning',T),'');assert.throws(()=>C.sendNote(s,'xia','再问',T));assert.throws(()=>C.cleanText('a'.repeat(101),100));assert.throws(()=>C.cleanText('  ',100))});
test('incoming save and decline are private and stop re-injection',()=>{const s=fresh();const n=C.injectNote(s,'xia',T);C.incomingAction(s,n.id,'save');assert.equal(n.status,'saved');C.incomingAction(s,n.id,'decline');assert.equal(n.status,'declined');assert.throws(()=>C.injectNote(s,'xia',T));assert.throws(()=>C.incomingAction(s,n.id,'reply','hi'));assert.equal(s.messages.xia.length,0);s.profile.allowNotes=false;assert.throws(()=>C.injectNote(s,'yu',T))});
test('replies retry without duplicate user message, both directions',()=>{const s=fresh();contact(s);assert(C.hasContact(s,'xia'));C.sendMessage(s,'xia','周末呢',T);assert.throws(()=>C.sendMessage(s,'xia','重复',T));const length=s.messages.xia.length;C.finishReply(s,'xia','喜欢散步',T);assert.equal(s.messages.xia.length,length+1);assert.equal(C.finishReply(s,'xia','重复',T),false);const n=C.injectNote(s,'yu',T);C.incomingAction(s,n.id,'reply','很高兴认识你',T);assert(C.hasContact(s,'yu'));assert(s.pending.yu);C.finishReply(s,'yu','你也是',T);assert.equal(s.messages.yu.length,3)});
test('feelings never imply intent or authorization',()=>{const s=fresh();C.recordFeeling(s,'xia',95,'想继续聊',T);assert.equal(s.reviews.xia,undefined);assert.equal(s.feelings.xia[0].score,95);assert.throws(()=>C.recordFeeling(s,'xia',101));assert.throws(()=>C.recordFeeling(s,'xia',20.5))});
test('mutual outcome requires current explicit consent and spends once',()=>{const s=fresh();contact(s);C.review(s,'xia','closer',true,T);s.scenarios.xia={intent:'closer',authorized:true,cycle:0};const result=C.confirmHeart(s,'xia',T);assert(result.mutual);assert.throws(()=>C.confirmHeart(s,'xia',T));assert(!JSON.stringify(result).includes('score'));s.offsetDays=7;assert(C.confirmationReason(s,'xia',T).includes('当期'));C.review(s,'xia','closer',true,T);s.scenarios.xia={intent:'exploring',authorized:true,cycle:1};assert.equal(C.confirmHeart(s,'xia',T).mutual,false)});
test('unavailable people consume no quota, withdrawal and block take effect',()=>{const s=fresh();contact(s);C.review(s,'xia','closer',true,T);s.scenarios.xia.authorized=false;assert.throws(()=>C.confirmHeart(s,'xia',T));assert.equal(s.confirmations.length,0);s.scenarios.xia.authorized=true;C.review(s,'xia','closer',false,T);assert.throws(()=>C.confirmHeart(s,'xia',T));C.review(s,'xia','closer',true,T);C.blockPerson(s,'xia');assert.equal(s.reviews.xia.authorized,false);assert.throws(()=>C.sendMessage(s,'xia','hello',T));assert.throws(()=>C.confirmHeart(s,'xia',T))});
test('persistence round trip and reset',()=>{const s=fresh();contact(s);C.recordFeeling(s,'xia',60,'备注',T);const copy=JSON.parse(JSON.stringify(s));assert(C.validState(copy));assert.deepEqual(copy,s);const reset=fresh();assert.equal(reset.messages.xia.length,0);assert.equal(reset.offsetDays,0);assert(!C.validState({version:2}))});
test('damaged nested storage is rejected before rendering',()=>{const s=fresh();s.messages.xia=[null];assert.equal(C.validState(s),false);s.messages.xia=[];s.scenarios.xia={};assert.equal(C.validState(s),false)});
