import {chromium} from '../runtime/test-tools/node_modules/playwright-core/index.mjs';
import {createServer} from '../server.mjs';
import {openDatabase} from '../lib/db.mjs';
import {register,COOKIE_NAME} from '../lib/auth.mjs';
import {saveMatchingProfile,storeTags} from '../lib/matching.mjs';
import {draw,decide,drawDay} from '../lib/draw.mjs';
import {DRAW_PEOPLE} from '../public/core.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const db=openDatabase(':memory:');
const goldTags={selfTags:['真诚','重视沟通','喜欢自然'],desiredTags:['喜欢自然']};
const guidance={interpretations:[{intent:'想继续交流',confidence:50,reason:'主动接话'},{intent:'分享兴趣',confidence:35,reason:'关注生活'},{intent:'礼貌回应',confidence:15,reason:'需要更多信息'}],suggestions:[{label:'分享生活',text:'我也喜欢周末散步。'},{label:'继续聊聊',text:'你平时喜欢去哪儿？'},{label:'轻松接话',text:'听起来很舒服。'}]};
const server=createServer({configured:true,base:'https://test.invalid/v1',key:'TEST_ONLY_KEY',model:'test'},{db,fetchImpl:async(_url,opt)=>{
 const system=JSON.parse(opt.body).messages.filter(m=>m.role==='system').map(m=>m.content).join('\n');
 const content=system.includes('提取匹配标签')?JSON.stringify(goldTags):system.includes('intent')||system.includes('interpretations')?JSON.stringify(guidance):'你好，很高兴和你分享今天的小风景。';
 return new Response(JSON.stringify({choices:[{message:{content}}]}),{status:200});
}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});fs.mkdirSync('runtime/screenshots',{recursive:true});const errors=[];
function seed(name,tags=goldTags){const a=register(db,{username:name,password:'password12'});db.prepare('UPDATE users SET allow_notes=0 WHERE id=?').run(a.user.id);saveMatchingProfile(db,a.user.id,{selfIntro:'我喜欢散步和自然，重视真诚的沟通。',desiredIntro:'我希望遇见喜欢自然、愿意分享日常的人。'});storeTags(db,a.user.id,tags);return a}
async function pageFor(a,size={width:390,height:844},reducedMotion='no-preference'){
 const context=await browser.newContext({viewport:size,reducedMotion});await context.addCookies([{name:COOKIE_NAME,value:a.token,url:base}]);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/Content Security Policy|Refused to apply|Refused to execute/.test(m.text()))errors.push(m.text())});await page.goto(base);if(await page.locator('.entry-skip').count())await page.locator('.entry-skip').click();await page.locator('.daily-encounter').waitFor();await page.waitForFunction(()=>document.querySelector('.draw-quota')?.textContent.includes('不限次数'));return {page,context};
}
try{
 const a=seed('draw_browser_gold');const {page,context}=await pageFor(a);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:width<720?844:900});assert.equal(await page.locator('.collection-empty').count(),2);assert.equal(await page.locator('.person-card').count(),3);assert(!await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await page.screenshot({path:`runtime/screenshots/draw-idle-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'开启今日相遇',exact:true}).click();await page.locator('.draw-stage.is-revealing.tier-gold').waitFor();const first=db.prepare('SELECT id FROM draw_records WHERE user_id=?').get(a.user.id).id;await page.screenshot({path:'runtime/screenshots/draw-gold-animation.png',fullPage:true});await page.reload();await page.getByRole('button',{name:'喜欢 · 留在窗边'}).waitFor();assert.equal(db.prepare('SELECT COUNT(*) AS n FROM draw_records WHERE user_id=?').get(a.user.id).n,1);assert.equal(db.prepare('SELECT id FROM draw_records WHERE user_id=?').get(a.user.id).id,first);
 await page.getByRole('button',{name:'喜欢 · 留在窗边'}).click();await page.locator('.collection-card').filter({hasText:'林澈'}).waitFor();assert.equal(await page.locator('.collection-empty').count(),1);assert(await page.getByRole('button',{name:'开启今日相遇',exact:true}).isDisabled());assert((await page.locator('.draw-status').textContent()).includes('没有新的合适人选'));await page.reload();await page.locator('.collection-card').filter({hasText:'林澈'}).waitFor();await page.locator('.collection-card').filter({hasText:'林澈'}).getByRole('button',{name:'递张纸条',exact:true}).click();await page.getByLabel('纸条内容').fill('你好，很高兴和你聊聊周末的风景。');await page.getByRole('button',{name:/递出纸条/}).click();await page.getByRole('button',{name:'让 AI 回应这张纸条'}).click();await page.locator('.vn-character-photo[src="/character/lin-watercolor.png"]').waitFor();await page.locator('.vn-character-photo').evaluate(i=>i.decode());assert.equal(await page.locator('.vn-character-photo').evaluate(i=>Math.round(i.getBoundingClientRect().bottom)),844);await page.screenshot({path:'runtime/screenshots/draw-lin-chat.png',fullPage:true});
 await page.locator('.menu-btn').click();await page.locator('.menu-nav').getByRole('button',{name:'遇见',exact:true}).click();await page.locator('.collection-card').filter({hasText:'林澈'}).getByRole('button',{name:'移除',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.collection-empty').length===2);assert.equal(db.prepare('SELECT COUNT(*) AS n FROM draw_cooldowns WHERE user_id=?').get(a.user.id).n,1);await context.close();
 for(const [tier,extra] of [['purple',['喜欢音乐','喜欢美食']],['blue',['喜欢音乐','喜欢美食','喜欢电影']]]){
  const tags={selfTags:goldTags.selfTags,desiredTags:['外向','真诚','喜欢运动','喜欢旅行','喜欢自然',...extra]},u=seed('draw_browser_'+tier,tags);const c=await pageFor(u);await c.page.getByRole('button',{name:'开启今日相遇'}).click();await c.page.locator('.draw-stage.is-revealing.tier-'+tier).waitFor();await c.page.getByRole('button',{name:'跳过动画'}).click();await c.page.screenshot({path:`runtime/screenshots/draw-${tier}-390.png`,fullPage:true});await c.page.getByRole('button',{name:'不喜欢 · 跳过'}).click();await c.page.locator('.draw-idle-card').waitFor();await c.context.close();
 }

 const continuous=seed('draw_unlimited',{selfTags:['真诚','重视沟通','喜欢音乐','喜欢美食'],desiredTags:['真诚','重视沟通','有耐心','喜欢美食']});
 const u=await pageFor(continuous,{width:390,height:844},'reduce');
 for(let i=0;i<3;i++){await u.page.getByRole('button',{name:'开启今日相遇',exact:true}).click();await u.page.getByRole('button',{name:'不喜欢 · 跳过'}).click();await u.page.locator('.draw-idle-card').waitFor();}
 assert.equal(db.prepare('SELECT COUNT(*) AS n FROM draw_records WHERE user_id=? AND day=?').get(continuous.user.id,drawDay(Date.now())).n,3);await u.context.close();
 const full=seed('draw_browser_full');db.prepare('DELETE FROM draw_collection WHERE user_id=?').run(full.user.id);for(let i=0;i<5;i++){let p;if(i<3)p={...DRAW_PEOPLE[i],kind:'virtual',score:100,tier:'gold',selfIntro:'已收藏的虚拟人物',sharedTags:['喜欢自然']};else{const realUser=seed('draw_browser_real_'+i);db.prepare('UPDATE users SET allow_notes=1 WHERE id=?').run(realUser.user.id);p={id:realUser.user.id,name:realUser.user.name,kind:'real',score:100,tier:'gold',selfIntro:'喜欢自然，也愿意认真交流的真实注册用户。',sharedTags:['喜欢自然']}}db.prepare('INSERT INTO draw_collection(user_id,kind,person_id,snapshot,added_at) VALUES(?,?,?,?,?)').run(full.user.id,p.kind,p.id,JSON.stringify(p),i)}
 const f=await pageFor(full,{width:1440,height:900});assert(await f.page.getByRole('button',{name:'收藏已满',exact:true}).isDisabled());await f.page.screenshot({path:'runtime/screenshots/draw-full-1440.png',fullPage:true});await f.page.setViewportSize({width:320,height:844});assert(!await f.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));await f.page.screenshot({path:'runtime/screenshots/draw-full-320.png',fullPage:true});await f.page.locator('.collection-card').first().getByRole('button',{name:'移除',exact:true}).click();await f.page.getByRole('button',{name:'开启今日相遇',exact:true}).waitFor();assert(await f.page.getByRole('button',{name:'开启今日相遇',exact:true}).isDisabled());assert((await f.page.locator('.draw-status').textContent()).includes('没有新的合适人选'));await f.context.close();
 const reduced=seed('draw_browser_reduced');const r=await pageFor(reduced,{width:390,height:844},'reduce');await r.page.getByRole('button',{name:'开启今日相遇'}).click();await r.page.getByRole('button',{name:'喜欢 · 留在窗边'}).waitFor();assert.equal(await r.page.locator('.is-revealing').count(),0);
 for(const p of DRAW_PEOPLE){const alpha=await r.page.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();const c=document.createElement('canvas');c.width=i.naturalWidth;c.height=i.naturalHeight;const ctx=c.getContext('2d');ctx.drawImage(i,0,0);return [i.naturalWidth,i.naturalHeight,ctx.getImageData(0,0,1,1).data[3]]},p.sprite);assert.equal(alpha[2],0);}
 await r.context.close();assert.deepEqual(errors,[]);console.log('PASS: responsive draw and collection, three color animations, reload recovery, like/skip/remove, new virtual chat, full capacity and reduced motion.');
}finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));db.close();}
