import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createServer,makeMessages,parseSuggestions,completion} from '../server.mjs';
const config={configured:true,base:'https://example.invalid/v1',key:'TEST_SECRET_NOT_FOR_BROWSER',model:'test-model'};
const suggestions={suggestions:[{label:'关心',text:'今天过得怎么样？'},{label:'接话',text:'很高兴听你分享。'},{label:'了解',text:'你喜欢怎样度过周末？'}]};
const profile={name:'安',habit:'慢热',topic:'今天如何'};
async function withServer(t,options={}){const server=createServer(config,options);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r)}));return `http://127.0.0.1:${server.address().port}`}
test('private data is excluded from upstream messages',()=>{const body={personId:'xia',messages:[],profile,feelings:{xia:99},reviews:{secret:true},confirmations:['private'],context:'greeting'};const built=JSON.stringify(makeMessages(body,'reply'));assert(!built.includes('99'));assert(!built.includes('secret'));assert(!built.includes('private'));assert(!built.includes(config.key))});
test('suggestion validation',()=>{assert.equal(parseSuggestions(JSON.stringify(suggestions)).length,3);assert.equal(parseSuggestions('```json\n'+JSON.stringify(suggestions)+'\n```').length,3);assert.throws(()=>parseSuggestions('{}'));assert.throws(()=>parseSuggestions('{broken'));assert.throws(()=>makeMessages({personId:'unknown',messages:[]},'reply'))});
test('HTTP route protections, static files and secret exclusion',async t=>{const url=await withServer(t);const status=await(await fetch(url+'/api/status')).text();assert(status.includes('test-model'));assert(!status.includes(config.key));assert.equal((await fetch(url+'/.env')).status,404);assert.equal((await fetch(url+'/server.mjs')).status,404);assert.equal((await fetch(url+'/')).status,200);const cross=await fetch(url+'/api/check',{method:'POST',headers:{Origin:'https://other.example','Content-Type':'application/json'},body:'{}'});assert.equal(cross.status,403);assert.equal((await fetch(url+'/api/check',{method:'POST',body:'{}'})).status,403)});
test('mock upstream validates authorization and successful API flows',async t=>{let sent;const url=await withServer(t,{fetchImpl:async(u,opt)=>{sent={u,opt};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(suggestions)}}]}),{status:200})}});const r=await fetch(url+'/api/suggestions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({personId:'xia',messages:[],profile})});assert.equal(r.status,200);assert.equal((await r.json()).suggestions.length,3);assert.equal(sent.u,config.base+'/chat/completions');assert.equal(sent.opt.headers.Authorization,'Bearer '+config.key)});
test('missing config, auth, rate limit, malformed output and network error',async()=>{await assert.rejects(()=>completion({...config,configured:false},[]),e=>e.code==='NOT_CONFIGURED');for(const [status,code] of [[401,'AUTH'],[429,'RATE_LIMIT'],[500,'UPSTREAM']])await assert.rejects(()=>completion(config,[],async()=>new Response('private vendor response '+config.key,{status})),e=>e.code===code&&!e.message.includes(config.key));await assert.rejects(()=>completion(config,[],async()=>new Response('oops')),e=>e.code==='FORMAT');await assert.rejects(()=>completion(config,[],async()=>{throw new Error(config.key)}),e=>e.code==='NETWORK'&&!e.message.includes(config.key));await assert.rejects(()=>completion(config,[],async()=>{throw new DOMException('timeout','TimeoutError')}),e=>e.code==='TIMEOUT')});
